import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("ships the Linux AI control plane and removes starter content", async () => {
  const [page, consoleSource, layout, packageJson, styles] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/console.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);

  assert.match(page, /<Console \/>/);
  assert.match(layout, /Linux\/AI Control Plane/);
  assert.match(consoleSource, /營運總覽/);
  assert.match(consoleSource, /更新盤點/);
  assert.match(consoleSource, /APT \+ CANONICAL SECURITY INTELLIGENCE/);
  assert.match(consoleSource, /全程不安裝套件/);
  assert.match(consoleSource, /\/api\/patch-inventory/);
  assert.match(consoleSource, /\/api\/patch-inventory\/policy/);
  assert.match(consoleSource, /自動更新風險盤點/);
  assert.match(consoleSource, /安全更新告警門檻/);
  assert.match(consoleSource, /盤點全部主機/);
  assert.match(consoleSource, /Linux 更新與 CVE 風險/);
  assert.match(consoleSource, /Canonical 公告比對完成/);
  assert.match(consoleSource, /CVE 資料未完成/);
  assert.match(consoleSource, /維運優先級不是 CVSS 分數/);
  assert.match(consoleSource, /securityCount/);
  assert.match(consoleSource, /package-risk/);
  assert.match(styles, /\.security-package-table/);
  assert.match(styles, /\.patch-page/);
  assert.match(consoleSource, /主機基準/);
  assert.match(consoleSource, /READ-ONLY LINUX SECURITY BASELINE/);
  assert.match(consoleSource, /不代表完整 CIS 認證/);
  assert.match(consoleSource, /\/api\/security-baselines/);
  assert.match(consoleSource, /\/api\/security-baselines\/policy/);
  assert.match(consoleSource, /自動安全基準政策/);
  assert.match(consoleSource, /最低安全分數/);
  assert.match(consoleSource, /自動巡檢排程中心/);
  assert.match(consoleSource, /巡檢執行紀錄/);
  assert.match(consoleSource, /\/api\/automation/);
  assert.match(consoleSource, /立即執行/);
  assert.match(consoleSource, /查看結果/);
  assert.match(consoleSource, /INSPECTION EVIDENCE/);
  assert.match(consoleSource, /\/api\/automation\/runs/);
  assert.match(consoleSource, /檢查全部主機/);
  assert.match(consoleSource, /安全分數趨勢/);
  assert.match(consoleSource, /至少完成兩次檢查/);
  assert.match(consoleSource, /scoreDelta/);
  assert.match(styles, /\.baseline-trend/);
  assert.match(styles, /\.baseline-page/);
  assert.match(consoleSource, /平台健檢/);
  assert.match(consoleSource, /CONTROL PLANE SELF OBSERVABILITY/);
  assert.match(consoleSource, /\/api\/platform-health/);
  assert.match(consoleSource, /只讀檢查中央服務/);
  assert.match(styles, /\.platform-health-page/);
  assert.match(consoleSource, /安全中心/);
  assert.match(consoleSource, /IDENTITY AND SESSION SECURITY/);
  assert.match(consoleSource, /登出我的其他裝置/);
  assert.match(consoleSource, /登入安全政策/);
  assert.match(consoleSource, /允許失敗次數/);
  assert.match(consoleSource, /登入紀錄保留天數/);
  assert.match(consoleSource, /\/api\/security\/policy/);
  assert.match(consoleSource, /\/api\/security\/sessions/);
  assert.match(consoleSource, /最近登入紀錄/);
  assert.match(styles, /\.security-page/);
  assert.match(consoleSource, /完整 UI 行為稽核/);
  assert.match(consoleSource, /ui\.click/);
  assert.match(consoleSource, /ui\.field\.change/);
  assert.match(consoleSource, /ui\.scroll\.depth/);
  assert.match(consoleSource, /自動佈署/);
  assert.match(consoleSource, /SSH 終端/);
  assert.match(consoleSource, /hosts\/bootstrap\/inspect/);
  assert.match(consoleSource, /WebSocket/);
  assert.match(consoleSource, /登入管理平台/);
  assert.match(consoleSource, /用戶管理/);
  assert.match(consoleSource, /群組管理/);
  assert.match(consoleSource, /告警中心/);
  assert.match(consoleSource, /BACKGROUND MONITOR/);
  assert.match(consoleSource, /資源趨勢/);
  assert.match(consoleSource, /新增告警規則/);
  assert.match(consoleSource, /通知管道/);
  assert.match(consoleSource, /發送測試通知/);
  assert.match(consoleSource, /notifications\/test/);
  assert.match(consoleSource, /備份管理/);
  assert.match(consoleSource, /中央備份與災難復原/);
  assert.match(consoleSource, /可靠性報表/);
  assert.match(consoleSource, /\/api\/reliability/);
  assert.match(consoleSource, /立即備份/);
  assert.match(consoleSource, /BACKUP AND RESTORE DRILLS/);
  assert.match(consoleSource, /COLD STANDBY READINESS/);
  assert.match(consoleSource, /SSH 私鑰與中央 \.env 必須由管理者另外保管/);
  assert.match(consoleSource, /下載中央復原封存/);
  assert.match(consoleSource, /download\/recovery/);
  assert.match(consoleSource, /READ-ONLY STANDBY PREFLIGHT/);
  assert.match(consoleSource, /執行冷備主機唯讀檢查/);
  assert.match(consoleSource, /prepare-cold-standby\.sh/);
  assert.match(consoleSource, /高風險安裝不會由中央遠端執行/);
  assert.match(consoleSource, /POSTGRESQL STREAMING REPLICATION/);
  assert.match(consoleSource, /資料庫串流複寫/);
  assert.match(consoleSource, /\/api\/replication\/status/);
  assert.match(consoleSource, /configure-postgres-primary\.sh/);
  assert.match(styles, /\.replication-center/);
  assert.match(consoleSource, /AI 主機診斷/);
  assert.match(consoleSource, /EVIDENCE-BASED AI ANALYSIS/);
  assert.match(consoleSource, /不會自動執行/);
  assert.match(consoleSource, /執行免費診斷/);
  assert.match(consoleSource, /不產生 API 費用/);
  assert.match(consoleSource, /\/api\/diagnostics/);
  assert.match(consoleSource, /ai\.manage/);
  assert.match(styles, /\.diagnostic-layout/);
  assert.match(consoleSource, /安全維運任務/);
  assert.match(consoleSource, /APPROVED CONTROLLED RUNBOOKS/);
  assert.match(consoleSource, /建立待核准任務/);
  assert.match(consoleSource, /由告警建立維運任務/);
  assert.match(consoleSource, /\/api\/alert-events\//);
  assert.match(consoleSource, /告警處理歷程/);
  assert.match(consoleSource, /事件時間線與結案/);
  assert.match(consoleSource, /回收卡住任務/);
  assert.match(consoleSource, /安全重試/);
  assert.match(consoleSource, /系統版本與更新準備/);
  assert.match(styles, /\.incident-timeline/);
  assert.match(styles, /\.pagination/);
  assert.match(consoleSource, /處理歷程/);
  assert.match(styles, /\.wide-modal/);
  assert.match(consoleSource, /確認並執行高風險任務/);
  assert.match(consoleSource, /ref={runbookRef}/);
  assert.match(consoleSource, /請選擇 Runbook/);
  assert.match(consoleSource, /需由另一位使用者核准/);
  assert.match(consoleSource, /受控寫入/);
  assert.match(consoleSource, /重新檢查權限/);
  assert.match(consoleSource, /maintenance-readiness/);
  assert.match(consoleSource, /\/api\/tasks\/readiness/);
  assert.match(consoleSource, /核准有效期限/);
  assert.match(consoleSource, /核准已過期/);
  assert.match(consoleSource, /主機資產盤點/);
  assert.match(consoleSource, /READ-ONLY ASSET & DRIFT INVENTORY/);
  assert.match(consoleSource, /\/api\/asset-inventory\/scan/);
  assert.match(consoleSource, /\/api\/asset-inventory\/policy/);
  assert.match(consoleSource, /偵測到設定漂移/);
  assert.match(consoleSource, /自動盤點與漂移告警/);
  assert.match(consoleSource, /盤點政策/);
  assert.match(consoleSource, /SHA-256/);
  assert.match(consoleSource, /tasks\.approve/);
  assert.match(consoleSource, /設定版控/);
  assert.match(consoleSource, /LOCAL GIT CONFIGURATION HISTORY/);
  assert.match(consoleSource, /不包含密碼、私鑰或通知 Token/);
  assert.match(consoleSource, /\/api\/config-versions/);
  assert.match(consoleSource, /FOUR-EYES RESTORE WORKFLOW/);
  assert.match(consoleSource, /等待其他管理者核准/);
  assert.match(consoleSource, /請輸入 RESTORE 確認/);
  assert.match(styles, /\.task-records/);
  assert.match(consoleSource, /\/api\/backups/);
  assert.match(consoleSource, /外部存活監控/);
  assert.match(consoleSource, /OUT-OF-BAND AVAILABILITY/);
  assert.match(consoleSource, /心跳正常/);
  assert.match(consoleSource, /上次中斷/);
  assert.match(consoleSource, /持續時間/);
  assert.match(consoleSource, /watchdogOutages/);
  assert.match(consoleSource, /line: "LINE"/);
  assert.match(consoleSource, /sms: "SMS Gateway"/);
  assert.match(consoleSource, /等待重試/);
  assert.match(consoleSource, /notification-retries/);
  assert.match(consoleSource, /HttpOnly/);
  assert.match(consoleSource, /重設密碼/);
  assert.match(consoleSource, /重新產生密碼/);
  assert.match(consoleSource, /確認新增/);
  assert.match(consoleSource, /密碼規則/);
  assert.match(consoleSource, /所屬群組/);
  assert.match(consoleSource, /PASSWORD POLICY/);
  assert.match(consoleSource, /left\.id === "administrators"/);
  assert.match(consoleSource, /授予權限/);
  assert.match(styles, /flex-direction:row!important/);
  assert.match(styles, /\.user-columns/);
  assert.match(styles, /\.group-columns/);
  assert.match(consoleSource, /Lock/);
  assert.doesNotMatch(`${page}${layout}${packageJson}`, /codex-preview|react-loading-skeleton/);
});
